// frontend/platform/src/routes/callback/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { authStore } from '$lib/auth';
	import { Loader2, AlertCircle } from 'lucide-svelte';
	import * as Card from '$lib/components/ui/card';
	import { Button } from '$lib/components/ui/button';

	let error = $state<string | null>(null);

	onMount(async () => {
		try {
			await authStore.handleCallback();
			
			// Hole gespeicherte Return URL oder nutze Dashboard als Default
			const returnUrl = sessionStorage.getItem('auth_return_url') || '/';
			sessionStorage.removeItem('auth_return_url');
			console.log('[Callback] Redirecting to:', returnUrl);
			
			goto(returnUrl);
		} catch (err) {
			console.error('[Callback] Error:', err);
			error = err instanceof Error ? err.message : 'Authentication failed';
		}
	});
</script>

<!-- Callback page renders outside of normal layout -->
<div class="flex min-h-screen items-center justify-center bg-background p-4">
	{#if error}
		<Card.Root class="w-full max-w-md">
			<Card.Header class="text-center">
				<div class="flex justify-center mb-4">
					<div class="flex h-14 w-14 items-center justify-center rounded-full bg-destructive/10">
						<AlertCircle class="h-8 w-8 text-destructive" />
					</div>
				</div>
				<Card.Title class="text-destructive">Authentication Error</Card.Title>
				<Card.Description>
					There was a problem completing your login.
				</Card.Description>
			</Card.Header>
			<Card.Content>
				<p class="text-sm text-muted-foreground text-center">{error}</p>
			</Card.Content>
			<Card.Footer class="flex justify-center">
				<Button href="/" variant="outline">Return to Login</Button>
			</Card.Footer>
		</Card.Root>
	{:else}
		<Card.Root class="w-full max-w-md">
			<Card.Content class="pt-6">
				<div class="text-center space-y-4">
					<Loader2 class="h-8 w-8 animate-spin mx-auto text-primary" />
					<div>
						<p class="font-medium">Completing authentication...</p>
						<p class="text-sm text-muted-foreground">Please wait while we verify your credentials.</p>
					</div>
				</div>
			</Card.Content>
		</Card.Root>
	{/if}
</div>

// frontend/src/pages/Callback.tsx
/**
 * OAuth Callback Page
 * Handles the redirect from ZITADEL after login
 */

import { createSignal, onMount, Show } from "solid-js";
import { useNavigate } from "@solidjs/router";

export default function Callback() {
  const navigate = useNavigate();
  const [error, setError] = createSignal<string | null>(null);

  onMount(async () => {
    try {
      // Get the stored UserManager settings from sessionStorage
      const settingsKey = Object.keys(sessionStorage).find(k => k.startsWith("oidc."));
      
      if (!settingsKey) {
        // No OIDC state found - might be a direct navigation
        console.log("No OIDC state found, redirecting to home...");
        navigate("/", { replace: true });
        return;
      }

      // The AuthProvider should handle this, but we add a timeout fallback
      const timeout = setTimeout(() => {
        console.log("Callback timeout - redirecting to home");
        navigate("/", { replace: true });
      }, 5000);

      // Wait for AuthProvider to process
      // The actual processing happens in AuthProvider's onMount
      return () => clearTimeout(timeout);
      
    } catch (err) {
      console.error("Callback error:", err);
      setError(err instanceof Error ? err.message : "Authentication failed");
    }
  });

  return (
    <div class="flex flex-col items-center justify-center min-h-[60vh] gap-4">
      <Show
        when={!error()}
        fallback={
          <div class="text-center space-y-4">
            <p class="text-destructive font-medium">Anmeldung fehlgeschlagen</p>
            <p class="text-muted-foreground text-sm">{error()}</p>
            <button
              onClick={() => navigate("/")}
              class="text-primary hover:underline"
            >
              Zurück zur Startseite
            </button>
          </div>
        }
      >
        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-primary" />
        <p class="text-muted-foreground">Authentifizierung wird verarbeitet...</p>
      </Show>
    </div>
  );
}
